import streamlit as st
import pandas as pd

# Page Setting
st.set_page_config(page_title="Dashboard",page_icon="📊",layout="wide")


# Styling
st.markdown("""
<style>

/* =========================================
   GLOBAL THEME
========================================= */

.stApp{
    background-color:#0F172A;
    color:#F8FAFC;
    font-family:"Segoe UI",sans-serif;
}

/* =========================================
   HIDE STREAMLIT DEFAULT UI
========================================= */

#MainMenu,
footer,
header{
    visibility:hidden;
}

/* =========================================
   HEADINGS
========================================= */

h1,h2,h3,h4,h5,h6{
    color:#F8FAFC;
    font-weight:700;
    letter-spacing:0.3px;
}

p,label{
    color:#CBD5E1;
}

/* =========================================
   BUTTONS
========================================= */

.stButton>button{

    width:100%;
    background:#3B82F6;
    color:white;

    border:none;
    border-radius:12px;

    padding:12px;

    font-size:16px;
    font-weight:600;

    transition:0.25s;
}

.stButton>button:hover{

    background:#2563EB;

    transform:translateY(-2px);

    box-shadow:0 6px 18px rgba(59,130,246,.30);

}

.stButton>button:active{

    transform:scale(.98);

}

/* =========================================
   METRIC CARDS
========================================= */

[data-testid="stMetric"]{

    background:#1E293B;

    border:1px solid #334155;

    border-radius:14px;

    padding:18px;

    transition:.25s;

}

[data-testid="stMetric"]:hover{

    border-color:#3B82F6;

    transform:translateY(-2px);

}

/* =========================================
   INFO / SUCCESS / WARNING
========================================= */

.stInfo,
.stSuccess,
.stWarning,
.stError{

    border-radius:12px;

}

/* =========================================
   INPUT BOX
========================================= */

.stTextInput input{

    background:#1E293B;

    color:white;

    border:1px solid #334155;

    border-radius:12px;

}

.stTextInput input:focus{

    border:1px solid #3B82F6;

}

/* =========================================
   SELECTBOX
========================================= */

.stSelectbox div[data-baseweb="select"]{

    background:#1E293B;

    border-radius:12px;

}

/* =========================================
   TEXT AREA
========================================= */

.stTextArea textarea{

    background:#1E293B;

    color:white;

    border-radius:12px;

    border:1px solid #334155;

}

/* =========================================
   FILE UPLOADER
========================================= */

[data-testid="stFileUploader"]{

    background:#1E293B;

    border:2px dashed #334155;

    border-radius:14px;

    padding:15px;

}

/* =========================================
   DATAFRAME
========================================= */

[data-testid="stDataFrame"]{

    border-radius:14px;

    overflow:hidden;

    border:1px solid #334155;

}

/* =========================================
   PROGRESS BAR
========================================= */

.stProgress > div > div > div{

    background:#3B82F6;

}

/* =========================================
   HORIZONTAL LINE
========================================= */

hr{

    border:none;

    border-top:1px solid #334155;

}


//  SCROLLBAR

::-webkit-scrollbar{

    width:8px;

}

::-webkit-scrollbar-track{

    background:#0F172A;

}

::-webkit-scrollbar-thumb{

    background:#475569;

    border-radius:10px;

}

::-webkit-scrollbar-thumb:hover{

    background:#64748B;

}

/* =========================================
   SIDEBAR (IF USED)
========================================= */

section[data-testid="stSidebar"]{

    background:#111827;

    border-right:1px solid #334155;

}

/* =========================================
   LINKS
========================================= */

a{

    color:#60A5FA;

    text-decoration:none;

}

a:hover{

    color:#93C5FD;

}

</style>
""", unsafe_allow_html=True)

st.title("📊 Resume Ranker AI Dashboard")
st.write("Top Ranked Candidates generated by AI")

st.divider()

# Read CSV
df = pd.read_csv("Final_ranked_candidate.csv")

#  Metrics
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Candidates Evaluated", "100000")

with col2:
    st.metric("Top Ranked", len(df))

with col3:
    st.metric("Highest Score", round(df["score"].max(), 3))

st.divider()

# Top 5 Candidates
st.subheader("🏆 Top 5 Candidates")

top5 = df.head(5)

st.dataframe(top5, use_container_width=True)

st.divider()

# Search Candidate
st.subheader("🔍 Search Candidate")

search = st.text_input("Enter Candidate ID")

if search:
    result = df[df["candidate id"].str.contains(search, case=False)]
else:
    result = df

st.dataframe(result, use_container_width=True)

st.divider()
# Download CSV
csv = df.to_csv(index=False).encode("utf-8")

st.download_button(
    label="⬇ Download Ranked CSV",
    data=csv,
    file_name="Final_ranked_candidate.csv",
    mime="text/csv"
)

st.divider()

st.success("✅ AI Ranking Completed Successfully")

st.caption("Developed By - Keshav Awasthi")